sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6.6

install:
  # Install Jekyll and dependencies
  - bundle install

before_script:
  - git config --global user.email "heeju01226@gmail.com"
  - git config --global user.name "Heeju Sim"

script: bundle exec rake site:deploy --quiet #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
    secure: "B+APRKArj2/3AZifKbsFTQ+pkZgG80ZSux/Orw+90GimcuT9KIRnbhsqFTfA/Q0nlzX2uWc5sgiHsoCQcGCpti0hEAviiK7PovAhmXADK9eukrwNyXkq0IXEbxhWmluBwqF7UXLyl1tkxKQb
             Fdby6CHLRJ+zPEDvKYuRkfidkb/Jdxb3LS9F2QH9hEryj3irZZVbWFaQoc4UWO10JsA+G7z4MzUmQnaevuh4C6/Q3/FvWi00VnUfNk/0SBt2cYYu78haw4IJPLKNf0lpAObbIQlADg+VFAMOEX9baXEm2NN
             lGVui4DIDgX9jilIJwsiuqrQ9k76btpuoQwJ83yiszWdtlEj7Ds1FwVMcLHa9BaNYqV9/VM3t7f/MYsb7jDBWlOaYQg7Mr/HFUsrMI6mWTjZUW1qGExQ2UOg8dOW7FoggljDGS6n70lT9yj36SLtCga8hGF
             cTCBdEEke0P4uJUlklYnyzxllFwXn4ku16euJXicKjiXvAFUDlMxdDRGNVJs/lXrc9NxfBsJekGUnqGtSsAIR78ugVhHMfW7qJHJ+06jjoIdhBPTgpN5Bie3PKgijwVjQWuKXlQte3kMs6iqlmXxw9hrMbL
             4zli8j8m8DE4gZzw/h1rkWSKWYRqrIpgpBBg/fWRBBDMavfOOHkDVQAbr65blnQFJJUT6rr7C4="
branches:
  only:
    - master